# Generated by Django 4.0.3 on 2022-03-20 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0002_alter_profile_branch_alter_profile_college_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_type', models.CharField(max_length=20)),
                ('name', models.CharField(default=None, max_length=30, primary_key=True, serialize=False)),
                ('description', models.TextField(default=None, max_length=1500)),
                ('guidelines', models.TextField(default=None, max_length=1500)),
                ('no_of_rounds', models.IntegerField(default=1)),
                ('round_1_details', models.TextField(default=None, max_length=300)),
                ('round_2_details', models.TextField(default=None, max_length=300)),
                ('round_3_details', models.TextField(default=None, max_length=300)),
                ('team_size', models.IntegerField(default=1)),
                ('mode_of_conduct', models.CharField(max_length=20)),
                ('event_core', models.CharField(default=None, max_length=50)),
                ('event_core_phone', models.CharField(default=999999999, max_length=10)),
                ('event_coordinator', models.CharField(default=None, max_length=50)),
                ('event_coordinator_phone', models.CharField(default=999999999, max_length=10)),
                ('cash_prize_1', models.IntegerField(default=500)),
                ('cash_prize_2', models.IntegerField(default=500)),
                ('cash_prize_3', models.IntegerField(default=500)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(default='CSE Block', max_length=30)),
                ('event_image', models.ImageField(blank=True, upload_to='events/')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('receipt_id', models.CharField(max_length=100)),
                ('mojo_id', models.CharField(max_length=100)),
                ('transaction_amount', models.IntegerField(default=400)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
