# Generated by Django 4.0.3 on 2022-03-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_event_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='department',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_cat',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
