# Generated by Django 4.0.3 on 2022-03-27 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_event_department_event_event_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('fullname', models.CharField(default=None, max_length=100)),
                ('wing', models.CharField(default=None, max_length=1000)),
                ('designation', models.CharField(default=None, max_length=1000)),
                ('gmail', models.CharField(default=None, max_length=1000)),
                ('instagram', models.CharField(default=None, max_length=1000)),
                ('twitter', models.CharField(default=None, max_length=1000)),
                ('facebook', models.CharField(default=None, max_length=1000)),
                ('linkedin', models.CharField(default=None, max_length=1000)),
                ('team_image', models.ImageField(upload_to='team_data/')),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='round_1_details',
            field=models.TextField(default=None, max_length=1500),
        ),
        migrations.AlterField(
            model_name='event',
            name='round_2_details',
            field=models.TextField(default=None, max_length=1500),
        ),
        migrations.AlterField(
            model_name='event',
            name='round_3_details',
            field=models.TextField(default=None, max_length=1500),
        ),
        migrations.CreateModel(
            name='EventRegister',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(default=None, max_length=1000)),
                ('first_name', models.CharField(default=None, max_length=1000)),
                ('last_name', models.CharField(default=None, max_length=1000)),
                ('email', models.EmailField(default=None, max_length=1000)),
                ('phone', models.CharField(default=999999999, max_length=10)),
                ('college_name', models.CharField(default='KL Vijayawada', max_length=30)),
                ('event_name', models.CharField(default=None, max_length=30)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
