# Generated by Django 4.0.3 on 2022-03-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_team_alter_event_round_1_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_cat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
    ]
