# Generated by Django 4.0.3 on 2022-03-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220327_1702'),
        ('home', '0006_alter_event_department_alter_event_event_cat_and_more'),
    ]

    operations = [
    ]
