# Generated by Django 4.0.3 on 2022-03-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_merge_20220327_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.CharField(default='CSE', max_length=50),
        ),
    ]
